---
title: "Analysis of 15q data"
output: github_document
---

# CRMetrics class


## Initializing a CRMetrics class

Load the library

```{r setup}
library(CRMetrics)
```

Initialize a new object of class `CRMetrics` with the path to the Cell Ranger output and a metadata file. 
The metadata file contains a column `sample` with the samples and optionally more columns with factors. 

```{r}
crm <- CRMetrics$new(data_path = "/data/15q/counts_premrna/", 
                     metadata_file = "/data/15q/metadata_15q_CRMetrics.csv",
                     n.cores = 50)
```


```{r}
crm$plotMedianUmi(comp_group = "condition")
crm$plotMedianUmi(comp_group = "age")
```

```{r}
crm$addDetailedMetrics()
```


```{r}
crm$plotGeneCounts(comp_group = "condition")
crm$plotUmiCounts(comp_group = "condition")
```

```{r}
crm$plotUMAP()
crm$plotDepth(cutoff_depth = 1e3, per_sample = FALSE)
crm$plotDepth(cutoff_depth = 1e3, per_sample = TRUE)
crm$plotUMAPDepth(cutoff_depth = 1e3, per_sample = FALSE)
# crm$plotUMAPDepth(cutoff_depth = 1e3, per_sample = TRUE) # Error
```


